#!/usr/bin/env bash

fetch_pvm_prefix()
{
   # TODO : pvm_configから取得する
   pvm_prefix="/home/masahiko/pvm"
}

# export other env variables
export use_version
export pvm_prefix pvm_lib pvm_script switch_version_sh use_version install_version switch_file

# fetch pvm_prefix
fetch_pvm_prefix

# set env variables
pvm_lib="$pvm_prefix/lib"
pvm_scrfipt="$pvm_prefix/script"
pvm_bin="$pvm_prefix/bin"
pvm_version="$pvm_prefix/version"

# META data
pvm_knownlist_file="$pvm_prefix/info/VERSIONS"
pvm_current_file="$pvm_prefix/info/CURRENT"

# set flags
export use_already_use

